Repository holunda-io/camunda-bpm-taskpool, pull requests merged in 2022-12, with the labels that each got.

#702 Feature/optional task query
  .github/workflows/codacy.yml
  view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/MongoViewService.kt
  view/mongo/src/test/kotlin/io/holunda/polyflow/view/mongo/service/PolyflowMongoServiceTestBase.kt
  view/mongo/src/test/kotlin/io/holunda/polyflow/view/mongo/service/PolyflowStages.kt
  view/simple/src/test/kotlin/io/holunda/polyflow/view/simple/service/SimpleTaskPoolServiceTest.kt
  view/simple/src/test/kotlin/io/holunda/polyflow/view/simple/service/TaskPoolStages.kt
Labels: Type: enhancement, Type: breaking

#705 Fixed update listener and assignment handling. Remove formKey from update commands
  core/datapool/datapool-core/src/main/kotlin/io/holunda/polyflow/datapool/core/DataPoolCoreAxonConfiguration.kt
  core/taskpool/taskpool-api/src/main/kotlin/io/holunda/camunda/taskpool/api/task/CamundaTaskEventType.kt
  core/taskpool/taskpool-api/src/main/kotlin/io/holunda/camunda/taskpool/api/task/EngineTaskCommandSorter.kt
  core/taskpool/taskpool-api/src/main/kotlin/io/holunda/camunda/taskpool/api/task/EngineTaskCommands.kt
  core/taskpool/taskpool-event/src/main/kotlin/io/holunda/camunda/taskpool/mapper/task/TaskFactoryMethods.kt
  docs/reference-guide/components/camunda-taskpool-collector.md
  integration/camunda-bpm/taskpool-collector/src/main/kotlin/io/holunda/polyflow/taskpool/DelegateTaskExtensions.kt
  integration/camunda-bpm/taskpool-collector/src/main/kotlin/io/holunda/polyflow/taskpool/collector/CamundaTaskpoolCollectorProperties.kt
  integration/camunda-bpm/taskpool-collector/src/main/kotlin/io/holunda/polyflow/taskpool/collector/task/TaskEventCollectorService.kt
  integration/camunda-bpm/taskpool-collector/src/main/kotlin/io/holunda/polyflow/taskpool/collector/task/enricher/ProcessVariablesTaskCommandEnricher.kt
  integration/camunda-bpm/taskpool-collector/src/test/kotlin/io/holunda/polyflow/taskpool/itest/TaskCollectorITest.kt
  integration/common/taskpool-sender/src/main/kotlin/io/holunda/polyflow/taskpool/sender/task/accumulator/EngineTaskCommandProjectionErrorDetector.kt
  integration/common/taskpool-sender/src/main/kotlin/io/holunda/polyflow/taskpool/sender/task/accumulator/ProjectingCommandAccumulator.kt
  integration/common/taskpool-sender/src/main/kotlin/io/holunda/polyflow/taskpool/sender/task/accumulator/SimpleEngineTaskCommandIntentDetector.kt
Labels: Type: bug, Status: In progress, Prio: Must

#707 batch commands
  bom/datapool-dependencies/pom.xml
  bom/parent/pom.xml
  bom/taskpool-dependencies/pom.xml
  core/bus-jackson/pom.xml
  core/datapool/datapool-api/pom.xml
  core/datapool/datapool-core/pom.xml
  core/datapool/datapool-event/pom.xml
  core/datapool/pom.xml
  core/taskpool/pom.xml
  core/taskpool/taskpool-api/pom.xml
  core/taskpool/taskpool-api/src/main/kotlin/io/holunda/camunda/taskpool/api/task/CamundaTaskEventType.kt
  core/taskpool/taskpool-api/src/main/kotlin/io/holunda/camunda/taskpool/api/task/EngineTaskCommandSorter.kt
  core/taskpool/taskpool-api/src/main/kotlin/io/holunda/camunda/taskpool/api/task/EngineTaskCommands.kt
  core/taskpool/taskpool-core/pom.xml
  core/taskpool/taskpool-core/src/main/kotlin/io/holunda/polyflow/taskpool/core/task/ExternalCommandHandler.kt
  core/taskpool/taskpool-core/src/main/kotlin/io/holunda/polyflow/taskpool/core/task/TaskAggregate.kt
  core/taskpool/taskpool-core/src/main/kotlin/io/holunda/polyflow/taskpool/core/task/TaskCreateCommandHandler.kt
  core/taskpool/taskpool-core/src/test/kotlin/io/holunda/polyflow/taskpool/core/task/TaskHandlerAggregateITest.kt
  core/taskpool/taskpool-event/pom.xml
  docs/reference-guide/components/common-taskpool-sender.md
  integration/camunda-bpm/engine-client/pom.xml
  integration/camunda-bpm/engine-client/src/test/kotlin/io/holunda/polyflow/client/camunda/process/ProcessStarterTest.kt
  integration/camunda-bpm/engine-client/src/test/kotlin/io/holunda/polyflow/client/camunda/task/TaskEventHandlerTest.kt
  integration/camunda-bpm/pom.xml
  integration/camunda-bpm/springboot-autoconfigure/pom.xml
  integration/camunda-bpm/springboot-autoconfigure/src/test/resources/banner.txt
  integration/camunda-bpm/springboot-starter/pom.xml
  integration/camunda-bpm/springboot-starter/src/test/resources/banner.txt
  integration/camunda-bpm/taskpool-collector/pom.xml
  integration/camunda-bpm/taskpool-collector/src/test/kotlin/io/holunda/polyflow/taskpool/collector/properties/CamundaTaskpoolCollectorPropertiesExtendedTest.kt
  integration/camunda-bpm/taskpool-collector/src/test/kotlin/io/holunda/polyflow/taskpool/collector/properties/CamundaTaskpoolCollectorPropertiesITest.kt
  integration/camunda-bpm/taskpool-collector/src/test/kotlin/io/holunda/polyflow/taskpool/collector/properties/PropertiesTestApplication.kt
  integration/camunda-bpm/taskpool-collector/src/test/kotlin/io/holunda/polyflow/taskpool/itest/BatchingTaskCollectorITest.kt
  integration/camunda-bpm/taskpool-collector/src/test/kotlin/io/holunda/polyflow/taskpool/itest/CollectorTestApplication.kt
  integration/camunda-bpm/taskpool-collector/src/test/kotlin/io/holunda/polyflow/taskpool/itest/JacksonDataFormatConfigurator.kt
  integration/camunda-bpm/taskpool-collector/src/test/kotlin/io/holunda/polyflow/taskpool/itest/ProcessDefinitionServiceITest.kt
  integration/camunda-bpm/taskpool-collector/src/test/kotlin/io/holunda/polyflow/taskpool/itest/TaskCollectorITest.kt
  integration/camunda-bpm/taskpool-collector/src/test/kotlin/io/holunda/polyflow/taskpool/itest/TestDriver.kt
  integration/camunda-bpm/taskpool-collector/src/test/resources/application-collector-itest.yml
  integration/common/datapool-sender/pom.xml
  integration/common/pom.xml
  integration/common/tasklist-url-resolver/pom.xml
  integration/common/taskpool-sender/pom.xml
  integration/common/taskpool-sender/src/main/kotlin/io/holunda/polyflow/taskpool/sender/SenderProperties.kt
  integration/common/taskpool-sender/src/main/kotlin/io/holunda/polyflow/taskpool/sender/task/TxAwareAccumulatingEngineTaskCommandSender.kt
  integration/common/variable-serializer/pom.xml
  pom.xml
  view/form-url-resolver/pom.xml
  view/jpa/pom.xml
  view/mongo/pom.xml
  view/mongo/src/test/kotlin/io/holunda/polyflow/view/mongo/utils/MongoLauncher.kt
  view/pom.xml
  view/simple/pom.xml
  view/view-api-client/pom.xml
  view/view-api/pom.xml
Labels: Type: enhancement, Prio: Must, Type: breaking

#724 fix: add missing @NestedConfigurationProperty so that configuration m…
  view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/TaskPoolMongoViewProperties.kt
Labels: Type: bug, Prio: Must
