Repository holunda-io/camunda-bpm-taskpool, pull requests merged in 2022-04, with the labels that each got.

#548 feat: move jackson bus configuration helpers in a separate artifact, …
  bom/parent/pom.xml
  bom/taskpool-dependencies/pom.xml
  core/bus-jackson/pom.xml
  core/bus-jackson/src/main/kotlin/io/holunda/polyflow/bus/jackson/DataEntryStateTypeMappingModule.kt
  core/bus-jackson/src/main/kotlin/io/holunda/polyflow/bus/jackson/JacksonExtensions.kt
  core/bus-jackson/src/main/kotlin/io/holunda/polyflow/bus/jackson/KotlinTypeInfo.kt
  core/bus-jackson/src/main/kotlin/io/holunda/polyflow/bus/jackson/VariableMapTypeMappingModule.kt
  core/bus-jackson/src/test/kotlin/io/holunda/polyflow/bus/jackson/DeserializersTest.kt
  core/taskpool/pom.xml
  core/taskpool/taskpool-core/pom.xml
  core/taskpool/taskpool-core/src/main/kotlin/io/holunda/polyflow/taskpool/core/JacksonExtensions.kt
  integration/common/taskpool-sender/pom.xml
  integration/common/taskpool-sender/src/main/kotlin/io/holunda/polyflow/taskpool/JacksonExtensions.kt
Labels: Type: enhancement

#550 Extract components, introduce more autoconfigs, removed tasklist-url-resolver and engine-client from the starter
  core/bus-jackson/pom.xml
  core/bus-jackson/src/main/kotlin/io/holunda/polyflow/bus/jackson/JacksonExtensions.kt
  core/bus-jackson/src/main/kotlin/io/holunda/polyflow/bus/jackson/annotation/AbstractQualifiedBeanCondition.kt
  core/bus-jackson/src/main/kotlin/io/holunda/polyflow/bus/jackson/annotation/ConditionalOnMissingQualifiedBean.kt
  core/bus-jackson/src/main/kotlin/io/holunda/polyflow/bus/jackson/annotation/OnMissingQualifiedBeanCondition.kt
  core/bus-jackson/src/main/kotlin/io/holunda/polyflow/bus/jackson/config/FallbackPayloadObjectMapperAutoConfiguration.kt
  core/bus-jackson/src/main/resources/META-INF/spring.factories
  core/bus-jackson/src/test/kotlin/io/holunda/polyflow/bus/jackson/DeserializersTest.kt
  core/taskpool/taskpool-core/src/main/kotlin/io/holunda/polyflow/taskpool/core/JacksonExtensions.kt
  docs/reference-guide/components/camunda-interaction-client.md
  docs/reference-guide/components/index.md
  docs/reference-guide/components/other-bus-jackson.md
  docs/reference-guide/components/other-tasklist-url-resolver.md
  integration/camunda-bpm/engine-client/pom.xml
  integration/camunda-bpm/engine-client/src/main/kotlin/io/holunda/polyflow/client/camunda/CamundaEngineClientAutoConfiguration.kt
  integration/camunda-bpm/engine-client/src/main/kotlin/io/holunda/polyflow/client/camunda/CamundaEngineClientProperties.kt
  integration/camunda-bpm/engine-client/src/main/kotlin/io/holunda/polyflow/client/camunda/EnableCamundaEngineClient.kt
  integration/camunda-bpm/engine-client/src/main/kotlin/io/holunda/polyflow/client/camunda/process/ProcessStarter.kt
  integration/camunda-bpm/engine-client/src/main/kotlin/io/holunda/polyflow/client/camunda/task/TaskEventHandlers.kt
  integration/camunda-bpm/engine-client/src/main/resources/META-INF/spring.factories
  integration/camunda-bpm/engine-client/src/test/kotlin/io/holunda/polyflow/client/camunda/CamundaEngineClientPropertiesExtendedTest.kt
  integration/camunda-bpm/engine-client/src/test/kotlin/io/holunda/polyflow/client/camunda/CamundaEngineClientPropertiesITest.kt
  integration/camunda-bpm/engine-client/src/test/kotlin/io/holunda/polyflow/client/camunda/CamundaEngineClientPropertiesTestApplication.kt
  integration/camunda-bpm/engine-client/src/test/kotlin/io/holunda/polyflow/client/camunda/process/ProcessStarterTest.kt
  integration/camunda-bpm/engine-client/src/test/kotlin/io/holunda/polyflow/client/camunda/task/TaskEventHandlerTest.kt
  integration/camunda-bpm/engine-client/src/test/resources/application-properties-itest.yaml
  integration/camunda-bpm/pom.xml
  integration/camunda-bpm/springboot-autoconfigure/pom.xml
  integration/camunda-bpm/springboot-autoconfigure/src/main/kotlin/io/holunda/polyflow/taskpool/EnableTaskpoolEngineSupport.kt
  integration/camunda-bpm/springboot-autoconfigure/src/main/kotlin/io/holunda/polyflow/taskpool/TaskpoolEngineSupportConfiguration.kt
  integration/camunda-bpm/springboot-starter/pom.xml
  integration/camunda-bpm/springboot-starter/src/main/resources/META-INF/spring.factories
  integration/camunda-bpm/taskpool-collector/src/main/kotlin/io/holunda/polyflow/taskpool/collector/CamundaTaskpoolCollectorConfiguration.kt
  integration/camunda-bpm/taskpool-collector/src/main/kotlin/io/holunda/polyflow/taskpool/collector/FallbackProcessVariablesCorrelatorConfiguration.kt
  integration/camunda-bpm/taskpool-collector/src/main/kotlin/io/holunda/polyflow/taskpool/collector/FallbackProcessVariablesFilterConfiguration.kt
  integration/common/datapool-sender/pom.xml
  integration/common/datapool-sender/src/main/kotlin/io/holunda/polyflow/datapool/DataEntrySenderConfiguration.kt
  integration/common/datapool-sender/src/main/kotlin/io/holunda/polyflow/datapool/DataEntrySenderProperties.kt
  integration/common/datapool-sender/src/main/kotlin/io/holunda/polyflow/datapool/EnableDataEntrySender.kt
  integration/common/datapool-sender/src/main/kotlin/io/holunda/polyflow/datapool/projector/DataEntryProjector.kt
  integration/common/tasklist-url-resolver/src/main/kotlin/io/holunda/polyflow/urlresolver/FallbackTasklistUrlResolverAutoConfiguration.kt
  integration/common/tasklist-url-resolver/src/main/resources/META-INF/spring.factories
  integration/common/taskpool-sender/src/main/kotlin/io/holunda/polyflow/taskpool/JacksonExtensions.kt
  integration/common/taskpool-sender/src/main/kotlin/io/holunda/polyflow/taskpool/sender/GenericTaskPublisher.kt
  integration/common/taskpool-sender/src/main/kotlin/io/holunda/polyflow/taskpool/sender/SenderConfiguration.kt
  integration/common/taskpool-sender/src/main/kotlin/io/holunda/polyflow/taskpool/sender/task/accumulator/projectProperties.kt
  integration/common/taskpool-sender/src/test/kotlin/io/holunda/polyflow/taskpool/sender/SenderPropertiesExtendedTest.kt
  integration/common/taskpool-sender/src/test/kotlin/io/holunda/polyflow/taskpool/sender/task/accumulator/ProjectPropertiesTest.kt
  mkdocs.yml
  view/form-url-resolver/pom.xml
  view/form-url-resolver/src/main/kotlin/io/holunda/polyflow/urlresolver/PropertyBasedFormUrlResolver.kt
  view/form-url-resolver/src/main/kotlin/io/holunda/polyflow/urlresolver/PropertyBasedFormUrlResolverConfiguration.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/JpaPolyflowViewDataEntryService.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/JpaPolyflowViewProcessDefinitionService.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/JpaPolyflowViewProcessInstanceService.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/JpaPolyflowViewTaskService.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/PolyflowJpaViewConfiguration.kt
  view/simple/src/main/kotlin/io/holunda/polyflow/view/simple/EnablePolyflowSimpleView.kt
  view/simple/src/main/kotlin/io/holunda/polyflow/view/simple/EnableTaskPoolSimpleView.kt
Labels: Type: bug

#545 Delay task deletion in Mongo View
  pom.xml
  view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/MongoViewService.kt
  view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/TaskPoolMongoViewConfiguration.kt
  view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/TaskPoolMongoViewProperties.kt
  view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/task/TaskChangeTracker.kt
  view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/task/TaskDocument.kt
  view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/task/TaskRepository.kt
  view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/task/TaskWithDataEntriesRepositoryExtensionImpl.kt
  view/mongo/src/test/kotlin/io/holunda/polyflow/view/mongo/TaskPoolMongoTestContext.kt
  view/mongo/src/test/kotlin/io/holunda/polyflow/view/mongo/service/PolyflowMongoServiceRetryTest.kt
  view/mongo/src/test/kotlin/io/holunda/polyflow/view/mongo/service/TaskChangeTrackerTest.kt
  view/mongo/src/test/kotlin/io/holunda/polyflow/view/mongo/task/TaskDocumentBuilder.kt
  view/mongo/src/test/kotlin/io/holunda/polyflow/view/mongo/task/TaskRepositoryExtensionImplITest.kt
Labels: Type: enhancement

#551 Update pa-frontend.md
  docs/examples/example-components/pa-frontend.md
Labels: Type: documentation
