Repository holunda-io/camunda-bpm-taskpool, pull requests merged in 2022-06, with the labels that each got.

#591 Change response type for query extension functions
  view/view-api/src/main/kotlin/QueryGatewayExt.kt
Labels: Type: bug, Prio: Must

#576 remove lambda from data class properties to make query serializable
  view/view-api/src/main/kotlin/query/task/TasksWithDataEntriesForUserQuery.kt
Labels: Type: bug, Status: In progress, Prio: Must

#610 Do not use public byLazy delegates properties in api data classes
  view/view-api/pom.xml
  view/view-api/src/main/kotlin/DataEntry.kt
  view/view-api/src/main/kotlin/Task.kt
  view/view-api/src/main/kotlin/query/data/DataEntriesForUserQuery.kt
  view/view-api/src/main/kotlin/query/data/DataEntriesQuery.kt
  view/view-api/src/test/kotlin/DataEntryTest.kt
  view/view-api/src/test/kotlin/TaskTest.kt
  view/view-api/src/test/kotlin/query/data/DataEntriesForUserQueryTest.kt
  view/view-api/src/test/kotlin/query/data/DataEntriesQueryTest.kt
Labels: Type: bug

#608 Update gav for axon-gateway-extension 0.1.0
  bom/parent/pom.xml
  view/jpa/pom.xml
  view/view-api/pom.xml
Labels: Type: dependencies

#601 Add getter for immutable maps
  view/simple/src/main/kotlin/io/holunda/polyflow/view/simple/service/SimpleDataEntryService.kt
  view/simple/src/main/kotlin/io/holunda/polyflow/view/simple/service/SimpleProcessDefinitionService.kt
  view/simple/src/main/kotlin/io/holunda/polyflow/view/simple/service/SimpleProcessInstanceService.kt
  view/simple/src/main/kotlin/io/holunda/polyflow/view/simple/service/SimpleProcessVariableService.kt
  view/simple/src/main/kotlin/io/holunda/polyflow/view/simple/service/SimpleTaskPoolService.kt
Labels: Type: enhancement
