Repository holunda-io/camunda-bpm-taskpool, pull requests merged in 2024-06, with the labels that each got.

#1004 Use flyway provisioned db for all ITests where database is needed. (D…
  integration/camunda-bpm/taskpool-collector/pom.xml
  integration/camunda-bpm/taskpool-collector/src/test/resources/application-collector-tx-itest.yml
  integration/camunda-bpm/taskpool-collector/src/test/resources/application-txjob-sender-itest.yml
  integration/camunda-bpm/taskpool-collector/src/test/resources/db/migrations/h2-postgresql/V0_0_1__postgres_engine_7.21.0.sql
  integration/camunda-bpm/taskpool-collector/src/test/resources/db/migrations/h2-postgresql/V0_0_2__postgres_identity_7.21.0.sql
Labels: Prio: Must, Type: breaking

#1006 Support correlations for data entries in JPA view
  bom/parent/pom.xml
  docs/reference-guide/components/view-jpa.md
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/JpaPolyflowViewDataEntryService.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/PolyflowJpaViewProperties.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/SpecificationExt.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/data/ConverterExt.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/data/DataEntryEntity.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/data/DataEntryPayloadAttributeEntity.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/data/DataEntryPayloadAttributeEntityId.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/data/DataEntryRepository.kt
  view/jpa/src/test/kotlin/io/holunda/polyflow/view/jpa/JpaPolyflowViewServiceDataEntryCorrelationITest.kt
  view/jpa/src/test/kotlin/io/holunda/polyflow/view/jpa/JpaPolyflowViewServiceDataEntryITest.kt
  view/jpa/src/test/kotlin/io/holunda/polyflow/view/jpa/SpecificationTest.kt
  view/jpa/src/test/kotlin/io/holunda/polyflow/view/jpa/data/DataEntryRepositoryITest.kt
  view/jpa/src/test/kotlin/io/holunda/polyflow/view/jpa/task/TaskRepositoryITest.kt
  view/jpa/src/test/resources/db/migrations/h2-postgresql/V0_0_15__jpa_view_correlation_payload.sql
  view/jpa/src/test/resources/db/migrations/h2-postgresql/V0_0_16__jpa_plf_data_entry_correlations.sql
Labels: Type: enhancement, Prio: Must, Type: breaking

#1014 Anonymize Data Entries
  core/datapool/datapool-api/src/main/kotlin/io/holunda/camunda/taskpool/api/business/DataEntryCommands.kt
  core/datapool/datapool-core/src/main/kotlin/io/holunda/polyflow/datapool/core/business/DataEntryAggregate.kt
  core/datapool/datapool-core/src/test/kotlin/io/holunda/polyflow/datapool/core/business/DataEntryAggregateTest.kt
  core/datapool/datapool-event/src/main/kotlin/io/holunda/camunda/taskpool/api/business/BusinessEvents.kt
  core/datapool/datapool-event/src/main/kotlin/io/holunda/camunda/taskpool/api/business/Mappers.kt
  integration/common/datapool-sender/src/main/kotlin/io/holunda/polyflow/datapool/sender/DataEntryCommandSender.kt
  integration/common/datapool-sender/src/main/kotlin/io/holunda/polyflow/datapool/sender/SimpleDataEntryCommandSender.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/JpaPolyflowViewDataEntryService.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/data/ConverterExt.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/data/DataEntryEventHandler.kt
  view/jpa/src/test/kotlin/io/holunda/polyflow/view/jpa/JpaPolyflowViewServiceDataEntryITest.kt
  view/jpa/src/test/kotlin/io/holunda/polyflow/view/jpa/TestFixtures.kt
  view/jpa/src/test/kotlin/io/holunda/polyflow/view/jpa/data/ConverterExtKtTest.kt
  view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/Converters.kt
  view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/MongoViewService.kt
  view/mongo/src/test/kotlin/io/holunda/polyflow/view/mongo/service/PolyflowStages.kt
  view/simple/src/main/kotlin/io/holunda/polyflow/view/simple/service/Converters.kt
  view/simple/src/main/kotlin/io/holunda/polyflow/view/simple/service/SimpleDataEntryService.kt
  view/simple/src/main/kotlin/io/holunda/polyflow/view/simple/service/SimpleTaskPoolService.kt
  view/simple/src/test/kotlin/io/holunda/polyflow/view/simple/service/ConvertersKtTest.kt
Labels: Type: enhancement, Status: In progress, Prio: Must
