Repository holunda-io/camunda-bpm-taskpool, pull requests merged in 2024-10, with the labels that each got.

#1042 feat(#1015): added property to enable payload attribute length valida…
  docs/reference-guide/components/view-jpa.md
  integration/common/variable-serializer/src/main/kotlin/VariableSerializer.kt
  integration/common/variable-serializer/src/test/kotlin/JsonPathWithValueTest.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/JpaPolyflowViewDataEntryService.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/JpaPolyflowViewTaskService.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/PolyflowJpaViewProperties.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/data/ConverterExt.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/task/ConverterExt.kt
Labels: Type: enhancement, Status: In progress, Prio: Should

#1061 Metadata generation for JPA view
  view/jpa/pom.xml
Labels: Type: bug, Prio: Must

#1060 Add date range operator for due date and follow-up date of tasks
  .github/dependabot.yml
  .github/workflows/codacy.yml
  .github/workflows/docs.yml
  docs/reference-guide/components/view-api.md
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/SpecificationExt.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/task/TaskRepository.kt
  view/jpa/src/test/kotlin/io/holunda/polyflow/view/jpa/JpaPolyflowViewServiceTaskITest.kt
  view/mongo/src/main/kotlin/io/holunda/polyflow/view/mongo/task/TaskWithDataEntriesRepositoryExtensionImpl.kt
  view/view-api/src/main/kotlin/filter/Filter.kt
  view/view-api/src/test/kotlin/filter/FilterTest.kt
Labels: Type: enhancement, Prio: Must

#1037 #1036: Use Event timestamp instead of Changlog Date to decide if the event should be applied
  docs/reference-guide/components/view-jpa.md
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/JpaPolyflowViewDataEntryService.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/PolyflowJpaViewProperties.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/data/ConverterExt.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/data/DataEntryEntity.kt
  view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/data/DataEntryEventHandler.kt
  view/jpa/src/test/kotlin/io/holunda/polyflow/view/jpa/JpaPolyflowViewServiceDataEntryCorrelationITest.kt
  view/jpa/src/test/kotlin/io/holunda/polyflow/view/jpa/JpaPolyflowViewServiceDataEntryITest.kt
  view/jpa/src/test/kotlin/io/holunda/polyflow/view/jpa/JpaPolyflowViewServiceTaskITest.kt
  view/jpa/src/test/kotlin/io/holunda/polyflow/view/jpa/TestFixtures.kt
  view/jpa/src/test/kotlin/io/holunda/polyflow/view/jpa/data/ConverterExtKtTest.kt
  view/jpa/src/test/resources/db/migrations/h2-postgresql/V0_0_7__jpa_view.sql
  view/jpa/src/test/resources/db/migrations/mariadb/V0_0_7__jpa_view.sql
Labels: Type: enhancement, Type: breaking
